### ISSUE TITLE
Donet SDK location Problem

### ISSUE THREAD

**Issue by enotar2020** [rebinf/Korduene#2]
Hey How are you doing,
I am glad you did that but I am not a real programmer.....yet!  Trying
I achieve to build the solution and Korduene open but of course no new solution load as Dotnet SDK not at the right location. I want mention that I have your last 0.9 version installed in my computer.
The question is where to put exactly DotNet SDK? ?Korduene\bin\Debug, where is that?
I Get     \net5.0Microsoft.Build.Exceptions.InvalidProjectFileException: 'The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.  C:\Users\enota\Documents\Korduene\Projects\WpfApp3\WpfApp3\WpfApp3.csproj'

_Output Error_
Exception thrown: 'Microsoft.Build.Exceptions.InvalidProjectFileException' in Microsoft.Build.dll
An unhandled exception of type 'Microsoft.Build.Exceptions.InvalidProjectFileException' occurred in Microsoft.Build.dll
The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.

I am also using a preview of dotnet sdk 5.0 with windows 10 insiders
That should be it.

Thanks

**Comment by rebinf** [comment]
Hi,

I'm good thanks, hope you're good as well.
This could be your starting point :)

I've just pushed workaround to address the SDK issue by setting environment variables to let msbuild know where the SDK is, so no need to copy anything (readme updated).

Do the following:
1. Update your local repository to the latest commit.
2. Rebuild the solution and Run Korduene (so it can set the environment variables, you only need to do this once).
3. Restart visual studio and run Korduene and you should be good to go.

Please note that this repository is not related to the previous version of Korduene, as this is a rewrite and it uses a different project system.

**Comment by enotar2020** [comment]
Thank you, all good here! As much as we can say so, new normal.
Well that works perfect and find first issue with toolbox and tool selection crashing.
It is late so I will take another look tomorrow.
Thanks for this. I hope I can contribute.

**Comment by rebinf** [comment]
You're welcome, create a new issue if there is anything, or create a pull request if you want to contribute to the repo.
