### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by anonimo82** [rebinf/Korduene#5]
Hello.
I wonder what's the current status for this project, beside C# support, which I'm not interested to.

Thanks in advance.

**Comment by rebinf** [comment]
Hi,
There is no active development, it's the source as it is.
Sorry.

**Comment by anonimo82** [comment]
No problem, just curious. Is the App functional enough?

**Comment by rebinf** [comment]
No, it's missing lots of functionality.

**Comment by anonimo82** [comment]
I see. Thanks.
